[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
name_registry = "8ut3Sq75sPmJweJFi9ZLWVEt6rhaneETWRromG9V8Laj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 300000 tests/**/*.ts"
