[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 4
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 4
